### PR TITLE
add skiptest decorator for failed module loading

### LINKED ISSUE #50: Skip unit tests when module import fails on macOS
Development / testing on macOS with compiled libs using arrow-cpp has symbol errors that have not been resolved. This is easy to resolve by using the `@unittest.skipTest` decorator when module fails to import.

### PR DESCRIPTION
**Pull request by ryanmwhitephd**
Resolves #50 
Should enable testing on Mac and linux, skipping tests when certain modules fail to load. 
@DominicParent if you have both os available, you can compare the unittests. 
Simply try:
`python -m unittest tests/test_filtercol.py`

this should run on linux with fwfr and filtercoltool built properly, but just skip on macOS when the module import fails.

### CODE REVIEW

**Comment by ryanmwhitephd** [comment]
I'll check the CI results.

**Comment by ryanmwhitephd** [comment]
Appears to be skipping the tests, rather than loading the module. I'll investigate further, hold off on the merge.

**Comment by ryanmwhitephd** [comment]
@DominicParent this is ready for review now.

**Review by DominicParent — APPROVED** [review]
Seems to work, approved.

**Pull request merged**
